config/routes.rb
resources :projects do
  resources :easy_baselines, :except => [:show, :edit, :update]
end

resources :easy_baseline_gantt, :only => :show

app/models/easy_baseline_source.rb
class EasyBaselineSource < ActiveRecord::Base

  belongs_to :baseline, class_name: 'Project'

  scope :issues, -> { where(:relation_type => 'Issue') }
  scope :versions, -> { where(:relation_type => 'Version') }

  scope :with_source, -> { where.not(:source_id => nil) }
  scope :without_source, -> { where(:source_id => nil) }

  scope :joins_source_versions, -> { joins("INNER JOIN #{Version.table_name} ON #{self.table_name}.source_id = #{Version.table_name}.id") }
  scope :joins_baseline_versions, -> { joins("INNER JOIN #{Version.table_name} ON #{self.table_name}.destination_id = #{Version.table_name}.id") }

  def source
    @source ||= self.relation_type.constantize.find(source_id)
  end

  def destination
    @destination ||= self.relation_type.constantize.find(destination_id)
  end

end

app/controllers/easy_baseline_gantt_controller.rb
class EasyBaselineGanttController < ApplicationController
  accept_api_auth :show

  before_action :find_baseline
  before_action :authorize

  def show
    # Wait for gantt modifications
    issue_ids = @project.issues.pluck(:id)
    version_ids = @project.versions.pluck(:id)

    b_table = EasyBaselineSource.table_name
    i_table = Issue.table_name
    v_table = Version.table_name

    @issues = @baseline.issues.
                        joins(:easy_baseline_source).
                        where(easy_baseline_sources: { source_id: issue_ids }).
                        pluck("#{i_table}.start_date, #{i_table}.due_date, #{i_table}.done_ratio, #{b_table}.source_id")

    @versions = @baseline.easy_baseline_sources.
                          versions.
                          joins_baseline_versions.
                          where(easy_baseline_sources: { source_id: version_ids }).
                          pluck("#{v_table}.effective_date, #{b_table}.source_id")

    respond_to do |format|
      format.api
    end
  end

  private

    def find_baseline
      @baseline = Project.includes(:easy_baseline_for).
                          where(id: params[:id]).
                          where.not(easy_baseline_for_id: nil).
                          first!
      @project = @baseline.easy_baseline_for
    rescue ActiveRecord::RecordNotFound
      render_404
    end

end

app/controllers/easy_baselines_controller.rb
class EasyBaselinesController < ApplicationController
  accept_api_auth :index, :create, :destroy

  before_action :find_project_by_project_id
  before_action :authorize
  before_action :authorize_baseline_source

  include Redmine::I18n
  include SortHelper

  def index
    @baselines = Project.where(easy_baseline_for: @project)
  end

  def new
    prepare_baseline
  end

  def create
    prepare_baseline

    Mailer.with_deliveries(false) do
      if @baseline.save(validate: false) && @baseline.copy(@project, only: ['versions', 'issues'], with_time_entries: false)
        # Easyredmine copies time on {copy_issues}
        @baseline.time_entries.destroy_all

        respond_to do |format|
          format.html {
            flash[:notice] = l(:notice_easy_baseline_created, project_name: @project.name)
            redirect_back_or_default project_easy_baselines_path(@project)
          }
          format.api  { render_api_ok }
        end
      else
        respond_to do |format|
          format.html { render :new }
          format.api  { render_validation_errors(@baseline) }
        end
      end
    end
  end

  def destroy
    @baseline = Project.find(params[:id])
    @baseline.destroy

    respond_to do |format|
      format.html {
        flash[:notice] = l(:notice_successful_delete)
        redirect_back_or_default project_easy_baselines_path(@project)
      }
      format.api { head :no_content }
    end
  end

  private

    def prepare_baseline(options={})
      options[:name] = params[:easy_baseline][:name] if params[:easy_baseline]

      @baseline = Project.copy_from(@project)
      @baseline.status = Project::STATUS_ARCHIVED
      # Without this hack it disables a modules on original project see http://www.redmine.org/issues/20512 for details
      @baseline.enabled_modules = []
      @baseline.enabled_module_names = @project.enabled_module_names
      @baseline.name =  options[:name] || (format_time(Time.now) + ' ' + @project.name)
      @baseline.identifier = options[:name].present? ? options[:name].parameterize : @project.identifier + '_' + Time.now.strftime('%Y%m%d%H%M%S')
      @baseline.easy_baseline_for_id = @project.id
      @baseline.parent = EasyBaseline.baseline_root_project
      # Project.copy_from change customized so CV are not copyied but moved
      # Already done in easyredmine
      @baseline.custom_values = @project.custom_values.map{|v| cloned_v = v.dup; cloned_v.customized = @baseline; cloned_v}
    end

    def authorize_baseline_source
      render_404 unless @project.easy_baseline_for.nil?
    end

end

app/views/easy_baselines/index.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:edit_baselines, @project) %>
    <%# todo: show modal to pick baseline's name %>
    <%#= link_to_function(l(:label_create_easy_baseline), "ysy.pro.baseline.openCreateModal()", :class => 'icon icon-add') %>
    <%= link_to(l(:label_create_easy_baseline), project_easy_baselines_path(@project), :method => :post, :class => 'icon icon-add') %>
  <% end %>
</div>

<h2><%= l(:label_easy_baselines) %></h2>

<table class="list">
<tr>
  <th><%= l(:field_name) %></th>
  <th><%= l(:field_project) %></th>
  <th></th>
</tr>

<% @baselines.each do |baseline| %>
  <tr class="<%= cycle 'odd', 'even' %>">
    <td><%= baseline.name %></td>
    <td><%= link_to baseline.easy_baseline_for.name, project_path(baseline.easy_baseline_for_id) %></td>
    <td class="buttons">
      <% if User.current.allowed_to?(:edit_baselines, @project) %>
        <%= link_to l("button_delete"), project_easy_baseline_path(@project, baseline),
              :method => 'delete', :class => "icon icon-del", :data => { :confirm => l(:text_are_you_sure) } %>
      <% end %>
    </td>
  </tr>
<% end %>

</table>

app/views/easy_baselines/new.html.erb
<%= error_messages_for(@baseline) %>
<%= button_to(l(:label_try_again), project_easy_baselines_path(@project, back_url: params[:back_url])) %>